(() => {
'use strict';
const $=id=>document.getElementById(id);
const brl=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const RESTAURANT_WHATSAPP='5519989860770';
const CART_KEY='akatsukyCart',CUSTOMER_KEY='akatsukyCustomer';
let menu=[],cart=[],cat='Todos',db=null,searchTerm='',storeOpen=true,deliveryFee=4,deferredPrompt=null;
function priceOf(x){const p=Number(x?.promoPrice);return p>0&&p<Number(x?.price||0)?p:Number(x?.price||0)}
function hasPromo(x){return Number(x?.promoPrice)>0&&Number(x.promoPrice)<Number(x.price||0)}
function syncTopCart(){const qty=cart.reduce((s,i)=>s+Number(i.q||0),0);const total=cart.reduce((s,i)=>{const x=menu.find(m=>Number(m.id)===Number(i.id));return s+(x?priceOf(x)*Number(i.q||0):0)},0);if($('navCartCount'))$('navCartCount').textContent=qty;if($('navCartTotal'))$('navCartTotal').textContent=total.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});if($('count'))$('count').textContent=`${qty} ${qty===1?'item':'itens'}`}
function persistCart(){localStorage.setItem(CART_KEY,JSON.stringify(cart));syncTopCart()}
function renderCats(){const cats=['Todos',...new Set(menu.map(x=>x.cat).filter(Boolean))];$('cats').innerHTML=cats.map(x=>`<button class="cat ${x===cat?'on':''}" data-cat="${esc(x)}">${esc(x)}</button>`).join('');document.querySelectorAll('.cat').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;renderCats();renderMenu()})}
function card(x,featured=false){const p=priceOf(x),old=Number(x.price||0),hp=hasPromo(x),disc=hp?Math.round((1-p/old)*100):0;const img=x.image||x.imageUrl||'';return `<article class="card product ${featured?'featuredCard':''}">${img?`<img class="productImage" src="${esc(img)}" alt="${esc(x.name)}" loading="lazy">`:''}<div class="catname">${esc(x.cat||'')}</div>${hp?`<span class="discount">🔥 ${disc}% OFF</span>`:''}<h3>${esc(x.name)}</h3><p>${esc(x.desc||'')}</p><div class="price">${hp?`<span class="oldPrice">${brl(old)}</span><span class="promoPrice">${brl(p)}</span>`:brl(p)}</div><button class="add" data-add="${Number(x.id)}" ${storeOpen?'':'disabled'}>+ ADICIONAR</button></article>`}
function bindAdd(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(Number(b.dataset.add)))}
function renderFeatured(){const el=$('promocoes');const box=$('featured');if(!el||!box)return;const list=menu.filter(x=>x.featured===true||x.featured==='true'||x.highlight===true||x.destaque===true||hasPromo(x));el.classList.toggle('hidden',!list.length);box.innerHTML=list.map(x=>card(x,true)).join('');bindAdd()}
function renderMenu(){const q=searchTerm.trim().toLowerCase();const list=menu.filter(x=>(cat==='Todos'||x.cat===cat)&&(!q||`${x.name} ${x.desc||''} ${x.cat||''}`.toLowerCase().includes(q)));$('menu').innerHTML=list.length?list.map(x=>card(x)).join(''):'<div class="empty wideEmpty">Nenhum produto encontrado.</div>';bindAdd();renderCart()}
function add(id){if(!storeOpen)return alert('A loja está fechada no momento.');const x=cart.find(i=>Number(i.id)===Number(id));x?x.q++:cart.push({id:Number(id),q:1});persistCart();renderCart()}
function del(id){const x=cart.find(i=>Number(i.id)===Number(id));if(x&&x.q>1)x.q--;else cart=cart.filter(i=>Number(i.id)!==Number(id));persistCart();renderCart()}
function clearCart(){cart=[];persistCart();renderCart()}
function renderCart(){let subtotal=0;const rows=cart.map(i=>{const x=menu.find(m=>Number(m.id)===Number(i.id));if(!x)return '';const p=priceOf(x);subtotal+=p*Number(i.q||0);return `<div class="cartrow"><span><b>${i.q}x</b> ${esc(x.name)}<small>${brl(p)} un.${hasPromo(x)?' • PROMOÇÃO':''}</small></span><b>${brl(p*i.q)}</b><div class="qtyControls"><button type="button" class="remove" data-del="${i.id}">−</button><button type="button" class="remove" data-inc="${i.id}">+</button></div></div>`}).join('');const fee=cart.length?Number(deliveryFee||0):0;const total=subtotal+fee;if($('cart')){$('cart').className=cart.length?'':'empty';$('cart').innerHTML=cart.length?rows+`<div class="cartSummary"><div><span>Subtotal</span><b>${brl(subtotal)}</b></div><div><span>🛵 Taxa de entrega</span><b>${brl(fee)}</b></div><div class="cartGrand"><span>Total</span><b>${brl(total)}</b></div></div><button type="button" class="clearCart" id="clearCart">🗑 Limpar pedido</button>`:'Carrinho vazio. Adicione produtos acima.';document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>del(Number(b.dataset.del)));document.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>add(Number(b.dataset.inc)));if($('clearCart'))$('clearCart').onclick=clearCart}syncTopCart();if($('total'))$('total').textContent=brl(total)}
function renderStoreStatus(){let e=$('storeStatus');if(!e){e=document.createElement('div');e.id='storeStatus';e.className='storeClosed';document.body.prepend(e)}e.classList.toggle('hidden',storeOpen);e.innerHTML=storeOpen?'<b>🟢 LOJA ABERTA</b><span>Estamos recebendo pedidos.</span>':'<b>🔴 LOJA FECHADA</b><span>No momento não estamos recebendo novos pedidos.</span>';document.querySelectorAll('.add').forEach(b=>b.disabled=!storeOpen)}
function setConnection(t,type='ok'){const e=$('connection');if(e){e.className='notice '+type;e.textContent=t}}
async function searchCep(){const c=$('cep').value.replace(/\D/g,'');if(c.length!==8)return alert('Digite um CEP válido.');const b=$('searchCep');b.disabled=true;b.textContent='Consultando...';try{const r=await fetch(`https://viacep.com.br/ws/${c}/json/`);const d=await r.json();if(d.erro)throw Error();$('street').value=d.logradouro||'';$('neighborhood').value=d.bairro||'';$('city').value=d.localidade||'';$('uf').value=d.uf||'';updateDeliveryByAddress()}catch(e){alert('Não foi possível consultar o CEP. Preencha o endereço manualmente.')}finally{b.disabled=false;b.textContent='🔎 Buscar CEP'}}
function updateDeliveryByAddress(){const city=($('city')?.value||'').trim().toLowerCase();const uf=($('uf')?.value||'').trim().toUpperCase();if(window.DeliveryRules?.calculate){deliveryFee=Number(window.DeliveryRules.calculate(city,uf)||deliveryFee)}else deliveryFee=(city.normalize('NFD').replace(/[\u0300-\u036f]/g,'')==='aguas de lindoia'&&uf==='SP')?4:8;renderCart()}
function saveCustomer(){localStorage.setItem(CUSTOMER_KEY,JSON.stringify(['name','phone','cep','street','number','neighborhood','city','uf','payment','notes'].reduce((o,k)=>(o[k]=$(k)?.value||'',o),{}))}
function loadCustomer(){try{const c=JSON.parse(localStorage.getItem(CUSTOMER_KEY)||'null');if(c)Object.entries(c).forEach(([k,v])=>{if($(k))$(k).value=v})}catch(e){}}
function maskPhone(v){v=v.replace(/\D/g,'').slice(0,11);return v.length<=10?v.replace(/(\d{2})(\d{4})(\d{0,4})/,'($1) $2-$3').replace(/-$/,''):v.replace(/(\d{2})(\d{5})(\d{0,4})/,'($1) $2-$3').replace(/-$/,'')}
function openWhatsApp(id,o){const itens=o.items.map(x=>`${x.qty}x ${x.name} — ${brl(x.price*x.qty)}`).join('\n'),c=o.customer;const msg=`🍣 *NOVO PEDIDO - AKATSUKY DELIVERY SUSHI*\n\nPedido: #${String(id||'LOCAL').slice(-6)}\nNome: ${c.name}\nCelular: ${c.phone}\n\n*Itens:*\n${itens}\n\n*Subtotal:* ${brl(o.subtotal)}\n*Taxa de entrega:* ${brl(o.deliveryFee)}\n*Total:* ${brl(o.total)}\n*Pagamento:* ${c.payment}\n\n*Endereço:*\n${c.street}, ${c.number}\n${c.neighborhood} - ${c.city}/${c.uf}\nCEP: ${c.cep}${c.notes?`\n\nObs.: ${c.notes}`:''}`;window.location.href=`https://wa.me/${RESTAURANT_WHATSAPP}?text=${encodeURIComponent(msg)}`}
async function submitOrder(e){e.preventDefault();if(!storeOpen)return alert('A loja está fechada no momento.');if(!cart.length)return alert('Adicione produtos ao carrinho.');saveCustomer();updateDeliveryByAddress();const items=cart.map(i=>{const x=menu.find(m=>Number(m.id)===Number(i.id));return x?{name:x.name,qty:i.q,price:priceOf(x),originalPrice:Number(x.price||0)}:null}).filter(Boolean);const subtotal=items.reduce((s,x)=>s+x.price*x.qty,0),fee=Number(deliveryFee||0),total=subtotal+fee;const customer={name:$('name').value.trim(),phone:$('phone').value.trim(),cep:$('cep').value,street:$('street').value.trim(),number:$('number').value.trim(),neighborhood:$('neighborhood').value.trim(),city:$('city').value.trim(),uf:$('uf').value.trim().toUpperCase(),payment:$('payment').value,notes:$('notes').value.trim()};const o={createdAt:firebase.database.ServerValue.TIMESTAMP,status:'recebido',subtotal,deliveryFee:fee,customer,items,total};let id='LOCAL-'+Date.now();try{if(db){const r=await db.ref('orders').push(o);id=r.key;localStorage.setItem('lastOrder',id);showTracking(id)}}catch(err){console.error(err);alert('O Firebase não aceitou o pedido. O pedido será aberto no WhatsApp mesmo assim.')}openWhatsApp(id,o);clearCart()}
function showTracking(id){if(!db||!id||id.startsWith('LOCAL-'))return;$('tracking')?.classList.remove('hidden');db.ref('orders/'+id).on('value',s=>{const o=s.val();if(!o||!$('trackingBox'))return;const steps=['recebido','preparando','saiu para entrega','entregue'],idx=Math.max(0,steps.indexOf(o.status));$('trackingBox').innerHTML=`<p><b>Pedido #${id.slice(-6)}</b> <span class="status">${String(o.status).toUpperCase()}</span></p><p>Subtotal: <b>${brl(o.subtotal??(Number(o.total||0)-Number(o.deliveryFee||0)))}</b> • Taxa: <b>${brl(o.deliveryFee||0)}</b> • Total: <b>${brl(o.total)}</b></p><div class="timeline">${steps.map((x,i)=>`<div class="step ${i<=idx?'active':''}">${x.toUpperCase()}</div>`).join('')}</div>`})}
function loadFirebase(){if(!window.firebase){setConnection('🟠 Firebase carregando...','warn');return setTimeout(loadFirebase,700)}try{if(!firebase.apps.length)firebase.initializeApp(window.AKATSUKY_FIREBASE_CONFIG);db=firebase.database();db.ref('settings/menu').on('value',s=>{const v=s.val();menu=v&&Array.isArray(v.items)?v.items.map((x,i)=>({...x,id:Number(x.id)||i+1,price:Number(x.price)||0,promoPrice:Number(x.promoPrice??x.promotionPrice??x.promo_price??x.precoPromocional??x.precoPromocao??0)})).filter(x=>x.name):[];renderCats();renderFeatured();renderMenu();setConnection('🟢 Sistema conectado • cardápio e pedidos em tempo real','ok')},err=>{console.error(err);setConnection('🟠 Firebase não autorizou o cardápio','warn')});db.ref('settings/storeOpen').on('value',s=>{storeOpen=s.val()!==false;renderStoreStatus();renderMenu();renderFeatured()});db.ref('settings/deliveryFee').on('value',s=>{const v=Number(s.val());if(Number.isFinite(v))deliveryFee=v;renderCart()})}catch(e){console.error(e);setConnection('🟠 Erro na configuração Firebase','warn')}}
window.addEventListener('DOMContentLoaded',()=>{$('searchCep').onclick=searchCep;if($('menuSearch'))$('menuSearch').oninput=e=>{searchTerm=e.target.value;renderMenu()};if($('phone'))$('phone').oninput=e=>e.target.value=maskPhone(e.target.value);if($('cep'))$('cep').oninput=e=>{let c=e.target.value.replace(/\D/g,'').slice(0,8);e.target.value=c.length>5?c.slice(0,5)+'-'+c.slice(5):c};['city','uf'].forEach(id=>$(id)?.addEventListener('input',updateDeliveryByAddress));$('orderForm').onsubmit=submitOrder;loadCustomer();try{cart=JSON.parse(localStorage.getItem(CART_KEY)||'[]').filter(i=>i&&i.id&&Number(i.q)>0)}catch(e){cart=[]}syncTopCart();renderCart();loadFirebase();const last=localStorage.getItem('lastOrder');if(last)showTracking(last);if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('install')?.classList.add('show')});$('installBtn')?.addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('install')?.classList.remove('show')}else alert("No celular, abra o menu do navegador e escolha 'Adicionar à tela inicial'.")})});
window.AKATSUKY_CART={syncTopCart,persistCart,getCart:()=>cart};
})();