(() => {
'use strict';
const $=id=>document.getElementById(id);let db=null,orders=[],uid=null,role=null,closing=null;
const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const dateKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function isToday(ts){const d=new Date(Number(ts||0));return d.toISOString().slice(0,10)===dateKey()}
function payment(v){v=String(v||'').toLowerCase();if(v.includes('pix'))return'pix';if(v.includes('crédito')||v.includes('credito'))return'credito';if(v.includes('débito')||v.includes('debito'))return'debito';return'dinheiro'}
function msg(t,err=false){$('connection').textContent=t;$('connection').className='notice'+(err?' err':'')}
function init(){try{firebase.initializeApp(window.AKATSUKY_FIREBASE_CONFIG);db=firebase.database();firebase.auth().onAuthStateChanged(async u=>{if(!u){$('login').classList.remove('hidden');$('app').classList.add('hidden');return}uid=u.uid;try{role=String((await db.ref(`users/${uid}/role`).once('value')).val()||'').toLowerCase();if(!['cashier','admin'].includes(role)){await firebase.auth().signOut();alert('Esta conta não tem permissão de caixa.');return}showApp()}catch(e){console.error(e);await firebase.auth().signOut();alert('Falha ao verificar a função do usuário.')}})}catch(e){console.error(e);msg('Erro ao iniciar o Firebase.',true)}}
function showApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden');msg(`🟢 Firebase conectado • caixa ${role}`);load()}
async function login(){const e=$('email').value.trim(),p=$('password').value;if(!e||!p){$('loginMsg').textContent='Informe e-mail e senha.';return}$('loginBtn').disabled=true;$('loginMsg').textContent='Entrando...';try{await firebase.auth().signInWithEmailAndPassword(e,p)}catch(err){$('loginMsg').textContent=`E-mail ou senha incorretos. Código: ${err.code||'erro'}`}finally{$('loginBtn').disabled=false}}
async function load(){const s=await db.ref('orders').once('value');orders=Object.entries(s.val()||{}).filter(([id,o])=>isToday(o.createdAt)).sort((a,b)=>Number(a[1].createdAt||0)-Number(b[1].createdAt||0));render();const c=await db.ref(`cashClosings/${dateKey()}`).once('value');closing=c.val()||null;if(closing){['opening','supply','withdrawal','countedCash','countedPix','countedCard'].forEach(k=>{if($(k)&&closing[k]!=null)$(k).value=Number(closing[k])});$('closeState').textContent=closing.finalized?'FINALIZADO':'ABERTO';if(closing.finalized)document.querySelectorAll('input').forEach(i=>i.disabled=true)}calc()}
function totals(){return orders.reduce((a,[id,o])=>{const v=Number(o.total||0),p=payment(o.customer?.payment);a.total+=v;a[p]+=v;return a},{total:0,dinheiro:0,pix:0,credito:0,debito:0})}
function render(){const t=totals();$('ordersCount').textContent=orders.length;$('sales').textContent=money(t.total);$('dinSales').textContent=money(t.dinheiro);$('pixSales').textContent=money(t.pix);$('rows').innerHTML=orders.map(([id,o])=>`<tr><td>#${esc(id.slice(-6))}</td><td>${esc(o.customer?.name||'')}</td><td>${esc(String(o.customer?.payment||'Dinheiro'))}</td><td>${money(o.total)}</td><td>${new Date(Number(o.createdAt||0)).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</td></tr>`).join('')||'<tr><td colspan="5">Nenhum pedido hoje.</td></tr>'}
function num(id){return Math.max(0,Number($(id).value||0))}
function calc(){const t=totals(),opening=num('opening'),supply=num('supply'),withdrawal=num('withdrawal'),cash=num('countedCash'),pix=num('countedPix'),card=num('countedCard');const expected=t.dinheiro+opening+supply-withdrawal;const counted=cash+pix+card;const diff=counted-t.total;$('expected').textContent=money(expected);$('counted').textContent=money(counted);$('difference').textContent=money(diff);return{opening,supply,withdrawal,countedCash:cash,countedPix:pix,countedCard:card,expected,counted,difference:diff,t}}
async function save(finalize=false){if(closing?.finalized&&!finalize){$('msg').textContent='Caixa já finalizado. Não é possível alterar.';return}const x=calc();const data={date:dateKey(),savedAt:firebase.database.ServerValue.TIMESTAMP,savedBy:uid,role,opening:x.opening,supply:x.supply,withdrawal:x.withdrawal,countedCash:x.countedCash,countedPix:x.countedPix,countedCard:x.countedCard,systemTotal:x.t.total,systemDinheiro:x.t.dinheiro,systemPix:x.t.pix,systemCredito:x.t.credito,systemDebito:x.t.debito,expectedCash:x.expected,countedTotal:x.counted,difference:x.difference,finalized:finalize};try{await db.ref(`cashClosings/${dateKey()}`).set(data);closing={...data,finalized:finalize};$('closeState').textContent=finalize?'FINALIZADO':'ABERTO';$('msg').textContent=finalize?'Caixa finalizado e bloqueado para alterações.':'Fechamento salvo com sucesso.';if(finalize)document.querySelectorAll('input').forEach(i=>i.disabled=true)}catch(e){console.error(e);$('msg').textContent='Erro ao salvar o fechamento.'}}
function bind(){['opening','supply','withdrawal','countedCash','countedPix','countedCard'].forEach(id=>$(id).oninput=calc);$('loginBtn').onclick=login;$('password').onkeydown=e=>{if(e.key==='Enter')login()};$('logout').onclick=()=>firebase.auth().signOut();$('save').onclick=()=>save(false);$('finalize').onclick=()=>{if(confirm('Finalizar o caixa de hoje? Depois disso os valores ficarão bloqueados.'))save(true)};$('print').onclick=()=>window.print()}
window.addEventListener('DOMContentLoaded',()=>{bind();init()});
})();
