(() => {
'use strict';
const $=id=>document.getElementById(id);
let db=null,user=null,orders=[],unsubs=[];
const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function msg(text,err=false){$('connection').textContent=text;$('connection').className='notice'+(err?' err':'')}
function rolePath(uid){return db.ref(`users/${uid}/role`)}
function isToday(ts){const d=new Date(Number(ts||0));return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===today()}
function payment(v){v=String(v||'').toLowerCase();if(v.includes('pix'))return 'PIX';if(v.includes('crédito')||v.includes('credito'))return 'Crédito';if(v.includes('débito')||v.includes('debito'))return 'Débito';return 'Dinheiro'}
function init(){try{firebase.initializeApp(window.AKATSUKY_FIREBASE_CONFIG);db=firebase.database();firebase.auth().onAuthStateChanged(async u=>{if(!u){showLogin();return}user=u;try{const snap=await rolePath(u.uid).once('value');const role=String(snap.val()||'').toLowerCase();if(!['admin','operator','cashier'].includes(role)){await firebase.auth().signOut();alert('Usuário sem permissão para o painel.');return}showApp(role)}catch(e){console.error(e);await firebase.auth().signOut();msg('Falha ao verificar a permissão do usuário.',true)}})}catch(e){console.error(e);msg('Erro ao conectar ao Firebase.',true)}}
function showLogin(){ $('login').classList.remove('hidden');$('app').classList.add('hidden') }
function showApp(role){$('login').classList.add('hidden');$('app').classList.remove('hidden');msg(`🟢 Firebase conectado • usuário ${user.email||''}`);$('toggleStore').textContent='🏪 Carregando loja...';listen();loadRules()}
async function login(){const email=$('email').value.trim(),pass=$('password').value;if(!email||!pass){$('loginMsg').textContent='Informe e-mail e senha.';return}$('loginBtn').disabled=true;$('loginMsg').textContent='Entrando...';try{await firebase.auth().signInWithEmailAndPassword(email,pass)}catch(e){console.error(e);$('loginMsg').textContent=`Falha no login: ${e.code||'erro'}`;$('loginBtn').textContent='ENTRAR NO PAINEL'}finally{$('loginBtn').disabled=false}}
function listen(){unsubs.forEach(f=>f&&f());unsubs=[];const or=db.ref('orders');const cb=s=>{const v=s.val()||{};orders=Object.entries(v).sort((a,b)=>Number(b[1]?.createdAt||0)-Number(a[1]?.createdAt||0));render()};or.on('value',cb);unsubs.push(()=>or.off('value',cb));const sr=db.ref('settings/storeOpen');const sc=s=>{const open=s.val()!==false;$('storeState').textContent=open?'ABERTA':'FECHADA';$('toggleStore').textContent=open?'🔴 Fechar loja':'🟢 Abrir loja';$('toggleStore').dataset.open=open?'1':'0'};sr.on('value',sc);unsubs.push(()=>sr.off('value',sc));}
function render(){const q=$('search').value.trim().toLowerCase(),f=$('filter').value;const arr=orders.filter(([id,o])=>{const text=`${id} ${o.customer?.name||''} ${o.customer?.phone||''}`.toLowerCase();return (!q||text.includes(q))&&(f==='todos'||o.status===f)});const todayRows=orders.filter(([id,o])=>isToday(o.createdAt));$('todayOrders').textContent=todayRows.length;$('newOrders').textContent=todayRows.filter(([id,o])=>o.status==='recebido').length;$('todayTotal').textContent=money(todayRows.reduce((s,[id,o])=>s+Number(o.total||0),0));$('orders').innerHTML=arr.length?arr.map(([id,o])=>card(id,o)).join(''):'<div class="panel">Nenhum pedido encontrado.</div>'}
function card(id,o){const c=o.customer||{},items=(o.items||[]).map(i=>`<div>${i.qty}x ${esc(i.name)} — ${money(Number(i.price||0)*Number(i.qty||0))}</div>`).join('');const st=['recebido','preparando','saiu para entrega','entregue'];const btns=st.map(x=>`<button class="${x===o.status?'on':''}" data-status="${esc(x)}" data-id="${esc(id)}">${x.toUpperCase()}</button>`).join('');return `<article class="order"><div class="orderTop"><b>Pedido #${esc(id.slice(-6))}</b><span class="status">${esc(o.status||'recebido')}</span></div><h3>${esc(c.name||'Cliente')}</h3><div class="sub">📞 ${esc(c.phone||'—')} • 📍 ${esc(c.street||'')} ${esc(c.number||'')} — ${esc(c.city||'')}/${esc(c.uf||'')}</div><div class="items">${items||'Sem itens'}</div><div class="orderTotal">Subtotal ${money(o.subtotal??(Number(o.total||0)-Number(o.deliveryFee||0)))} • Entrega ${money(o.deliveryFee||0)} • <b>Total ${money(o.total)}</b> • ${esc(payment(c.payment))}</div><div class="actions">${btns}<button data-delete="${esc(id)}" class="danger">🗑 Excluir</button></div></article>`}
async function status(id,status){try{const patch={status};patch[`statusTimes/${status}`]=firebase.database.ServerValue.TIMESTAMP;await db.ref(`orders/${id}`).update(patch)}catch(e){alert('Não foi possível alterar o pedido.')}}
async function del(id){if(!confirm('Excluir este pedido? Esta ação não pode ser desfeita.'))return;try{await db.ref(`orders/${id}`).remove()}catch(e){alert('Erro ao excluir pedido.')}}
async function toggleStore(){const open=$('toggleStore').dataset.open==='1';try{await db.ref('settings/storeOpen').set(!open)}catch(e){alert('Erro ao alterar o status da loja.')}}
async function loadRules(){try{const s=await db.ref('settings/deliveryRules').once('value');const v=s.val()||{};$('feeAguas').value=Number(v.aguasDeLindoia??v.aguas??4);$('feeOutras').value=Number(v.outrasCidades??v.outras??8)}catch(e){$('feeAguas').value=4;$('feeOutras').value=8}}
async function saveRules(){const a=Math.max(0,Number($('feeAguas').value||0)),o=Math.max(0,Number($('feeOutras').value||0));try{await db.ref('settings/deliveryRules').set({aguasDeLindoia:a,outrasCidades:o,savedAt:firebase.database.ServerValue.TIMESTAMP});$('rulesMsg').textContent=' • Taxas salvas com sucesso.'}catch(e){$('rulesMsg').textContent=' • Erro ao salvar taxas.'}}
function bind(){ $('loginBtn').onclick=login;$('password').onkeydown=e=>{if(e.key==='Enter')login()};$('logout').onclick=()=>firebase.auth().signOut();$('refresh').onclick=render;$('search').oninput=render;$('filter').onchange=render;$('toggleStore').onclick=toggleStore;$('saveRules').onclick=saveRules;$('orders').onclick=e=>{const s=e.target.closest('[data-status]');if(s)status(s.dataset.id,s.dataset.status);const d=e.target.closest('[data-delete]');if(d)del(d.dataset.delete)}}
window.addEventListener('DOMContentLoaded',()=>{bind();init()});
})();
