(()=>{
'use strict';
const $=id=>document.getElementById(id);
let db=null,user=null,orders=[],unsubs=[];
let lastReceivedIds=new Set(),initialOrdersLoaded=false,audioCtx=null,alertInterval=null;
const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function msg(text,err=false){$('connection').textContent=text;$('connection').className='notice'+(err?' err':'')}
function rolePath(uid){return db.ref(`users/${uid}/role`)}
function isToday(ts){const d=new Date(Number(ts||0));if(!Number.isFinite(d.getTime()))return false;const local=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return local===today()}
function payment(v){v=String(v||'').toLowerCase();if(v.includes('pix'))return 'PIX';if(v.includes('crédito')||v.includes('credito')||v.includes('cartão')||v.includes('cartao'))return 'Cartão';if(v.includes('débito')||v.includes('debito'))return 'Débito';return 'Dinheiro'}
function goBack(){location.href='index.html'}
function initAudio(){try{if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume().catch(()=>{});return true}catch(e){console.warn('Áudio indisponível',e);return false}}
function beep(){if(!initAudio())return;try{const now=audioCtx.currentTime;[0,0.18,0.36].forEach((delay,i)=>{const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type='sine';osc.frequency.value=i===1?1046:880;gain.gain.setValueAtTime(0.0001,now+delay);gain.gain.exponentialRampToValueAtTime(0.22,now+delay+0.02);gain.gain.exponentialRampToValueAtTime(0.0001,now+delay+0.15);osc.connect(gain);gain.connect(audioCtx.destination);osc.start(now+delay);osc.stop(now+delay+0.17)})}catch(e){console.warn('Falha no alerta sonoro',e)}}
function requestAudio(){initAudio();window.removeEventListener('pointerdown',requestAudio);window.removeEventListener('keydown',requestAudio)}
function flashAlert(on){document.body.classList.toggle('new-order-alert',!!on);if(on&&!alertInterval)alertInterval=setInterval(()=>document.body.classList.toggle('new-order-flash'),650);if(!on&&alertInterval){clearInterval(alertInterval);alertInterval=null;document.body.classList.remove('new-order-flash')}}
function ensureAlertCss(){if(document.getElementById('akatsukyAlertCss'))return;const s=document.createElement('style');s.id='akatsukyAlertCss';s.textContent='.order-waiting{animation:akatsukyPulse 1.1s infinite;border-color:#ef1731!important;box-shadow:0 0 0 2px #ef173155,0 0 28px #ef173155!important}.new-order-alert .notice:first-of-type{animation:akatsukyPulse 1s infinite}.new-order-flash .top{box-shadow:inset 0 -4px 0 #ef1731,0 0 24px #ef173166}.new-order-flash .stat.red:first-child{transform:scale(1.02)}@keyframes akatsukyPulse{0%,100%{opacity:1}50%{opacity:.55}}';document.head.appendChild(s)}
function notifyNewOrder(newOnes){if(!newOnes.length)return;beep();flashAlert(true);try{if('Notification'in window&&Notification.permission==='granted'){newOnes.forEach(([id,o])=>new Notification('🔔 NOVO PEDIDO - AKATSUKY',{body:`Pedido #${String(id).slice(-6)} • ${o.customer?.name||'Cliente'} • ${money(o.total)}`,tag:'akatsuky-'+id}))}}catch(e){console.warn('Notificação indisponível',e)}}
async function init(){try{if(!window.AKATSUKY_FIREBASE_CONFIG)throw new Error('Firebase config ausente');ensureAlertCss();firebase.initializeApp(window.AKATSUKY_FIREBASE_CONFIG);db=firebase.database();try{await firebase.auth().setPersistence(firebase.auth.Auth.Persistence.LOCAL)}catch(e){console.warn('Não foi possível definir persistência LOCAL:',e)}firebase.auth().onAuthStateChanged(async u=>{if(!u){showLogin();return}user=u;try{const snap=await rolePath(u.uid).once('value');const role=String(snap.val()||'').trim().toLowerCase();if(['garcom','garçom','garcon'].includes(role)){location.href='garcom.html';return}if(!['admin','operator','cashier'].includes(role)){alert('Usuário sem permissão para o painel.');return}showApp(role)}catch(e){console.error(e);msg('Não foi possível verificar a função do usuário. O login foi mantido; tente atualizar a página.',true)}})}catch(e){console.error(e);msg('Erro ao conectar ao Firebase.',true)}}
function showLogin(){$('login').classList.remove('hidden');$('app').classList.add('hidden')}
function showApp(role){$('login').classList.add('hidden');$('app').classList.remove('hidden');msg(`🟢 Firebase conectado • ${user.email||'usuário autenticado'}`);listen();loadRules();if('Notification'in window&&Notification.permission==='default')Notification.requestPermission().catch(()=>{});initAudio()}
async function login(){const email=$('email').value.trim(),pass=$('password').value;if(!email||!pass){$('loginMsg').textContent='Informe e-mail e senha.';return}initAudio();$('loginBtn').disabled=true;$('loginMsg').textContent='Entrando...';try{await firebase.auth().setPersistence(firebase.auth.Auth.Persistence.LOCAL);await firebase.auth().signInWithEmailAndPassword(email,pass)}catch(e){console.error(e);$('loginMsg').textContent=`Falha no login: ${e.code||'erro'}`;}finally{$('loginBtn').disabled=false}}
function listen(){unsubs.forEach(f=>f&&f());unsubs=[];initialOrdersLoaded=false;lastReceivedIds=new Set();const or=db.ref('orders');const cb=s=>{const v=s.val()||{};const next=Object.entries(v).sort((a,b)=>Number(b[1]?.createdAt||0)-Number(a[1]?.createdAt||0));const receivedNow=new Set(next.filter(([,o])=>String(o?.status||'').trim().toLowerCase()==='recebido').map(([id])=>id));if(initialOrdersLoaded){const fresh=next.filter(([id,o])=>receivedNow.has(id)&&!lastReceivedIds.has(id));if(fresh.length)notifyNewOrder(fresh)}else{initialOrdersLoaded=true}lastReceivedIds=receivedNow;orders=next;render();};or.on('value',cb,err=>{console.error(err);msg('🟠 Firebase conectado, mas não foi possível ler os pedidos. Verifique as regras.',true)});unsubs.push(()=>or.off('value',cb));const sr=db.ref('settings/storeOpen');const sc=s=>{const open=s.val()!==false;$('storeBadge').textContent=open?'🟢 LOJA ABERTA':'🔴 LOJA FECHADA';$('toggleStore').innerHTML=open?'🏪 <span>Fechar loja</span>':'🏪 <span>Abrir loja</span>';$('toggleStore').dataset.open=open?'1':'0'};sr.on('value',sc,err=>console.error(err));unsubs.push(()=>sr.off('value',sc));}
function render(){const q=$('search').value.trim().toLowerCase(),f=$('filter').value,date=$('dateFilter').value;const base=date==='today'?orders.filter(([,o])=>isToday(o.createdAt)):orders;let arr=base.filter(([id,o])=>{const c=o.customer||{};const text=`${id} ${c.name||''} ${c.phone||''} ${c.street||''} ${c.number||''} ${c.neighborhood||''} ${c.city||''} ${c.uf||''}`.toLowerCase();return(!q||text.includes(q))&&(f==='todos'?o.status!=='saiu para entrega':o.status===f)});if(f==='saiu para entrega')arr=base.filter(([id,o])=>{const c=o.customer||{};const text=`${id} ${c.name||''} ${c.phone||''} ${c.street||''} ${c.number||''} ${c.neighborhood||''} ${c.city||''} ${c.uf||''}`.toLowerCase();return(!q||text.includes(q))&&o.status==='saiu para entrega'});updateStats(base);$('orders').innerHTML=arr.length?arr.map(([id,o])=>card(id,o)).join(''):'<div class="empty">📭 Nenhum pedido encontrado com os filtros atuais.</div>'}
function updateStats(rows){const received=rows.filter(([,o])=>o.status==='recebido').length,preparing=rows.filter(([,o])=>o.status==='preparando').length,delivery=rows.filter(([,o])=>o.status==='saiu para entrega').length,delivered=rows.filter(([,o])=>o.status==='entregue').length;const total=rows.reduce((s,[,o])=>s+Number(o.total||0),0);$('todayOrders').textContent=rows.length;$('todayTotal').textContent=money(total);$('deliveryOrders').textContent=delivery;$('deliveredOrders').textContent=delivered;$('sumReceived').textContent=received;$('sumPreparing').textContent=preparing;$('sumDelivery').textContent=delivery;$('sumDelivered').textContent=delivered;let pix=0,card=0,cash=0;rows.forEach(([,o])=>{const p=payment(o.customer?.payment);if(p==='PIX')pix+=Number(o.total||0);else if(p.includes('Cartão')||p.includes('Débito'))card+=Number(o.total||0);else cash+=Number(o.total||0)});$('payPix').textContent=money(pix);$('payCard').textContent=money(card);$('payCash').textContent=money(cash)}
function statusClass(st){if(st==='aguardando')return 's-aguardando';if(st==='preparando')return 's-preparando';if(st==='saiu para entrega')return 's-saiu';if(st==='entregue')return 's-entregue';return 's-recebido'}
function printOrder(id){const o=orders.find(([x])=>x===id)?.[1];if(!o)return;const c=o.customer||{},items=(o.items||[]).map(i=>`<tr><td>${Number(i.qty||0)}x ${esc(i.name)}</td><td>${money(Number(i.price||0)*Number(i.qty||0))}</td></tr>`).join('');const w=window.open('','_blank','width=400,height=700');if(!w){alert('Permita pop-ups para imprimir a comanda.');return}w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Comanda #${esc(id.slice(-6))}</title><style>@page{size:80mm auto;margin:4mm}body{font-family:Arial,sans-serif;width:72mm;margin:0;font-size:12px}h2{text-align:center;margin:0 0 8px}.center{text-align:center}.line{border-top:1px dashed #000;margin:7px 0}table{width:100%;border-collapse:collapse}td:last-child{text-align:right}.total{font-size:16px;font-weight:bold}.obs{margin-top:8px}button{width:100%;padding:10px;margin-top:12px}@media print{button{display:none}}</style></head><body><h2>AKATSUKY SUSHI</h2><div class="center">COMANDA #${esc(id.slice(-6))}</div><div class="line"></div><b>Cliente:</b> ${esc(c.name||'Cliente')}<br><b>Telefone:</b> ${esc(c.phone||'—')}<br><b>Endereço:</b> ${esc(c.street||'')} ${esc(c.number||'')} - ${esc(c.neighborhood||'')}<br>${esc(c.city||'')}/${esc(c.uf||'')} - CEP ${esc(c.cep||'—')}<div class="line"></div><b>ITENS</b><table>${items}</table><div class="line"></div>Subtotal: ${money(o.subtotal??(Number(o.total||0)-Number(o.deliveryFee||0)))}<br>Entrega: ${money(o.deliveryFee||0)}<br>Pagamento: ${esc(payment(c.payment))}<div class="total">TOTAL: ${money(o.total)}</div>${c.notes?`<div class="obs"><b>Observação:</b> ${esc(c.notes)}</div>`:''}<button onclick="window.print()">🖨 IMPRIMIR</button><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`);w.document.close()}
function card(id,o){const c=o.customer||{},items=(o.items||[]).map(i=>`<div>${Number(i.qty||0)}x ${esc(i.name)} — ${money(Number(i.price||0)*Number(i.qty||0))}</div>`).join('');const st=['aguardando','recebido','preparando','saiu para entrega','entregue'];const btns=st.filter(x=>x!=='aguardando').map(x=>`<button class="${x===o.status?'on':''}" data-status="${esc(x)}" data-id="${esc(id)}">${x==='saiu para entrega'?'🛵 ':''}${x.toUpperCase()}</button>`).join('');const subtotal=Number(o.subtotal??(Number(o.total||0)-Number(o.deliveryFee||0)));const fee=Number(o.deliveryFee||0);const current=String(o.status||'aguardando');const accept=current==='aguardando'?`<button class="accept" data-status="recebido" data-id="${esc(id)}">✅ ACEITAR PEDIDO</button>`:'';return `<article class="order ${current==='aguardando'?'order-waiting':''}" data-order-id="${esc(id)}"><div class="orderHead"><span class="orderId">#${esc(id.slice(-6))}</span><span class="status ${statusClass(current)}">${current==='aguardando'?'🔴 AGUARDANDO':current==='recebido'?'🟢 RECEBIDO':esc(current.toUpperCase())}</span></div><div class="customer"><b>${esc(c.name||'Cliente')}</b><div class="meta">📞 ${esc(c.phone||'—')}<br>📍 ${esc(c.street||'')} ${esc(c.number||'')} — ${esc(c.neighborhood||'')} — ${esc(c.city||'')}/${esc(c.uf||'')}<br>📮 CEP ${esc(c.cep||'—')}</div></div><div class="gridOrder"><div class="items"><b>🍣 ITENS DO PEDIDO</b>${items||'<div>Sem itens</div>'}${c.notes?`<div style="margin-top:8px;color:#ffc14d">📝 ${esc(c.notes)}</div>`:''}</div><div class="totalBox"><div><span>Subtotal</span><b>${money(subtotal)}</b></div><div><span>Entrega</span><b style="color:#58b8ff">${money(fee)}</b></div><div><span>Pagamento</span><b class="payment">${esc(payment(c.payment))}</b></div><div class="total"><span>Total</span><b>${money(o.total)}</b></div></div><div><div class="meta">🕒 ${o.createdAt?new Date(Number(o.createdAt)).toLocaleString('pt-BR'):''}</div></div></div><div class="actions">${accept}${btns}<button data-print="${esc(id)}">🖨 IMPRIMIR COMANDA</button></div></article>`}
async function status(id,status){try{const patch={status};patch[`statusTimes/${status}`]=firebase.database.ServerValue.TIMESTAMP;await db.ref(`orders/${id}`).update(patch);if(status!=='recebido')flashAlert(false)}catch(e){console.error(e);alert('Não foi possível alterar o pedido.')}}
async function toggleStore(){const open=$('toggleStore').dataset.open==='1';try{await db.ref('settings/storeOpen').set(!open)}catch(e){console.error(e);alert('Erro ao alterar o status da loja.')}}
async function loadRules(){try{const s=await db.ref('settings/deliveryRules').once('value');const v=s.val()||{};$('feeAguas').value=Number(v.aguasDeLindoia??v.aguas??4);$('feeOutras').value=Number(v.outrasCidades??v.outras??8)}catch(e){$('feeAguas').value=4;$('feeOutras').value=8}}
async function saveRules(){const a=Math.max(0,Number($('feeAguas').value||0)),o=Math.max(0,Number($('feeOutras').value||0));try{await db.ref('settings/deliveryRules').set({aguasDeLindoia:a,outrasCidades:o,savedAt:firebase.database.ServerValue.TIMESTAMP});$('rulesMsg').textContent=' • Taxas salvas com sucesso.'}catch(e){console.error(e);$('rulesMsg').textContent=' • Erro ao salvar taxas.'}}
function bind(){$('loginBtn').onclick=login;$('password').onkeydown=e=>{if(e.key==='Enter')login()};$('logout').onclick=()=>firebase.auth().signOut();$('refresh').onclick=render;$('topRefresh').onclick=render;$('backBtn').onclick=goBack;$('search').oninput=render;$('filter').onchange=render;$('dateFilter').onchange=render;$('toggleStore').onclick=toggleStore;$('saveRules').onclick=saveRules;$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');$('orders').onclick=e=>{const s=e.target.closest('[data-status]');if(s){initAudio();status(s.dataset.id,s.dataset.status)}const p=e.target.closest('[data-print]');if(p)printOrder(p.dataset.print)}}
window.addEventListener('pointerdown',requestAudio,{once:true});window.addEventListener('keydown',requestAudio,{once:true});
window.addEventListener('DOMContentLoaded',()=>{bind();init()});
})();
window.addEventListener('DOMContentLoaded',()=>{
  const nav=document.querySelector('.nav');
  if(!nav) return;
  if(!nav.querySelector('[data-clientes-link]')){
    const link=document.createElement('a');
    link.href='clientes.html';
    link.dataset.clientesLink='1';
    link.innerHTML='👥 <span>Clientes</span>';
    nav.insertBefore(link,nav.children[1]||null);
  }
  if(!nav.querySelector('[data-sorteios-link]')){
    const link=document.createElement('a');
    link.href='sorteios.html';
    link.dataset.sorteiosLink='1';
    link.innerHTML='🎉 <span>Sorteios</span>';
    const clientLink=nav.querySelector('[data-clientes-link]');
    nav.insertBefore(link,clientLink?clientLink.nextSibling:null);
  }
});