(() => {
'use strict';
const $=id=>document.getElementById(id);
let db=null,user=null,orders=[],unsubs=[];
const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function msg(text,err=false){$('connection').textContent=text;$('connection').className='notice'+(err?' err':'')}
function rolePath(uid){return db.ref(`users/${uid}/role`)}
// Corrigido: o filtro "Hoje" usa a data local. Antes usava UTC e ocultava pedidos após 21h no Brasil.
function isToday(ts){const d=new Date(Number(ts||0));if(!Number.isFinite(d.getTime()))return false;const local=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return local===today()}
function payment(v){v=String(v||'').toLowerCase();if(v.includes('pix'))return 'PIX';if(v.includes('crédito')||v.includes('credito')||v.includes('cartão')||v.includes('cartao'))return 'Cartão';if(v.includes('débito')||v.includes('debito'))return 'Débito';return 'Dinheiro'}
function goBack(){if(history.length>1)history.back();else location.href='index.html'}
function init(){try{if(!window.AKATSUKY_FIREBASE_CONFIG)throw new Error('Firebase config ausente');firebase.initializeApp(window.AKATSUKY_FIREBASE_CONFIG);db=firebase.database();firebase.auth().onAuthStateChanged(async u=>{if(!u){showLogin();return}user=u;try{const snap=await rolePath(u.uid).once('value');const role=String(snap.val()||'').toLowerCase();if(!['admin','operator','cashier'].includes(role)){await firebase.auth().signOut();alert('Usuário sem permissão para o painel.');return}showApp(role)}catch(e){console.error(e);await firebase.auth().signOut();msg('Falha ao verificar a permissão do usuário.',true)}})}catch(e){console.error(e);msg('Erro ao conectar ao Firebase.',true)}}
function showLogin(){$('login').classList.remove('hidden');$('app').classList.add('hidden')}
function showApp(role){$('login').classList.add('hidden');$('app').classList.remove('hidden');msg(`🟢 Firebase conectado • ${user.email||'usuário autenticado'}`);listen();loadRules()}
async function login(){const email=$('email').value.trim(),pass=$('password').value;if(!email||!pass){$('loginMsg').textContent='Informe e-mail e senha.';return}$('loginBtn').disabled=true;$('loginMsg').textContent='Entrando...';try{await firebase.auth().signInWithEmailAndPassword(email,pass)}catch(e){console.error(e);$('loginMsg').textContent=`Falha no login: ${e.code||'erro'}`;}finally{$('loginBtn').disabled=false}}
function listen(){unsubs.forEach(f=>f&&f());unsubs=[];const or=db.ref('orders');const cb=s=>{const v=s.val()||{};orders=Object.entries(v).sort((a,b)=>Number(b[1]?.createdAt||0)-Number(a[1]?.createdAt||0));render()};or.on('value',cb);unsubs.push(()=>or.off('value',cb));const sr=db.ref('settings/storeOpen');const sc=s=>{const open=s.val()!==false;$('storeBadge').textContent=open?'🟢 LOJA ABERTA':'🔴 LOJA FECHADA';$('toggleStore').innerHTML=open?'🏪 <span>Fechar loja</span>':'🏪 <span>Abrir loja</span>';$('toggleStore').dataset.open=open?'1':'0'};sr.on('value',sc);unsubs.push(()=>sr.off('value',sc));}
function render(){const q=$('search').value.trim().toLowerCase(),f=$('filter').value,date=$('dateFilter').value;const base=date==='today'?orders.filter(([,o])=>isToday(o.createdAt)):orders;const arr=base.filter(([id,o])=>{const c=o.customer||{};const text=`${id} ${c.name||''} ${c.phone||''} ${c.street||''} ${c.number||''} ${c.neighborhood||''} ${c.city||''} ${c.uf||''}`.toLowerCase();return(!q||text.includes(q))&&(f==='todos'||o.status===f)});updateStats(base);$('orders').innerHTML=arr.length?arr.map(([id,o])=>card(id,o)).join(''):'<div class="empty">📭 Nenhum pedido encontrado com os filtros atuais.</div>'}
function updateStats(rows){const received=rows.filter(([,o])=>o.status==='recebido').length,preparing=rows.filter(([,o])=>o.status==='preparando').length,delivery=rows.filter(([,o])=>o.status==='saiu para entrega').length,delivered=rows.filter(([,o])=>o.status==='entregue').length;const total=rows.reduce((s,[,o])=>s+Number(o.total||0),0);$('todayOrders').textContent=rows.length;$('todayTotal').textContent=money(total);$('deliveryOrders').textContent=delivery;$('deliveredOrders').textContent=delivered;$('sumReceived').textContent=received;$('sumPreparing').textContent=preparing;$('sumDelivery').textContent=delivery;$('sumDelivered').textContent=delivered;let pix=0,card=0,cash=0;rows.forEach(([,o])=>{const p=payment(o.customer?.payment);if(p==='PIX')pix+=Number(o.total||0);else if(p.includes('Cartão')||p.includes('Débito'))card+=Number(o.total||0);else cash+=Number(o.total||0)});$('payPix').textContent=money(pix);$('payCard').textContent=money(card);$('payCash').textContent=money(cash)}
function statusClass(st){if(st==='preparando')return 's-preparando';if(st==='saiu para entrega')return 's-saiu';if(st==='entregue')return 's-entregue';return 's-recebido'}
function card(id,o){const c=o.customer||{},items=(o.items||[]).map(i=>`<div>${Number(i.qty||0)}x ${esc(i.name)} — ${money(Number(i.price||0)*Number(i.qty||0))}</div>`).join('');const st=['recebido','preparando','saiu para entrega','entregue'];const btns=st.map(x=>`<button class="${x===o.status?'on':''}" data-status="${esc(x)}" data-id="${esc(id)}">${x==='saiu para entrega'?'🛵 ':''}${x.toUpperCase()}</button>`).join('');const subtotal=Number(o.subtotal??(Number(o.total||0)-Number(o.deliveryFee||0)));const fee=Number(o.deliveryFee||0);return `<article class="order"><div class="orderHead"><span class="orderId">#${esc(id.slice(-6))}</span><span class="status ${statusClass(o.status)}">${esc(String(o.status||'recebido').toUpperCase())}</span></div><div class="customer"><b>${esc(c.name||'Cliente')}</b><div class="meta">📞 ${esc(c.phone||'—')}<br>📍 ${esc(c.street||'')} ${esc(c.number||'')} — ${esc(c.neighborhood||'')} — ${esc(c.city||'')}/${esc(c.uf||'')}<br>📮 CEP ${esc(c.cep||'—')}</div></div><div class="gridOrder"><div class="items"><b>🍣 ITENS DO PEDIDO</b>${items||'<div>Sem itens</div>'}${c.notes?`<div style="margin-top:8px;color:#ffc14d">📝 ${esc(c.notes)}</div>`:''}</div><div class="totalBox"><div><span>Subtotal</span><b>${money(subtotal)}</b></div><div><span>Entrega</span><b style="color:#58b8ff">${money(fee)}</b></div><div><span>Pagamento</span><b class="payment">${esc(payment(c.payment))}</b></div><div class="total"><span>Total</span><b>${money(o.total)}</b></div></div><div><div class="meta">🕒 ${o.createdAt?new Date(Number(o.createdAt)).toLocaleString('pt-BR'):''}</div></div></div><div class="actions">${btns}<button data-delete="${esc(id)}" class="danger">🗑 EXCLUIR</button></div></article>`}
async function status(id,status){try{const patch={status};patch[`statusTimes/${status}`]=firebase.database.ServerValue.TIMESTAMP;await db.ref(`orders/${id}`).update(patch)}catch(e){console.error(e);alert('Não foi possível alterar o pedido.')}}
async function del(id){if(!confirm('Excluir este pedido? Esta ação não pode ser desfeita.'))return;try{await db.ref(`orders/${id}`).remove()}catch(e){console.error(e);alert('Erro ao excluir pedido.')}}
async function toggleStore(){const open=$('toggleStore').dataset.open==='1';try{await db.ref('settings/storeOpen').set(!open)}catch(e){console.error(e);alert('Erro ao alterar o status da loja.')}}
async function loadRules(){try{const s=await db.ref('settings/deliveryRules').once('value');const v=s.val()||{};$('feeAguas').value=Number(v.aguasDeLindoia??v.aguas??4);$('feeOutras').value=Number(v.outrasCidades??v.outras??8)}catch(e){$('feeAguas').value=4;$('feeOutras').value=8}}
async function saveRules(){const a=Math.max(0,Number($('feeAguas').value||0)),o=Math.max(0,Number($('feeOutras').value||0));try{await db.ref('settings/deliveryRules').set({aguasDeLindoia:a,outrasCidades:o,savedAt:firebase.database.ServerValue.TIMESTAMP});$('rulesMsg').textContent=' • Taxas salvas com sucesso.'}catch(e){console.error(e);$('rulesMsg').textContent=' • Erro ao salvar taxas.'}}
function bind(){$('loginBtn').onclick=login;$('password').onkeydown=e=>{if(e.key==='Enter')login()};$('logout').onclick=()=>firebase.auth().signOut();$('refresh').onclick=render;$('topRefresh').onclick=render;$('backBtn').onclick=goBack;$('search').oninput=render;$('filter').onchange=render;$('dateFilter').onchange=render;$('toggleStore').onclick=toggleStore;$('saveRules').onclick=saveRules;$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');$('orders').onclick=e=>{const s=e.target.closest('[data-status]');if(s)status(s.dataset.id,s.dataset.status);const d=e.target.closest('[data-delete]');if(d)del(d.dataset.delete)}}
window.addEventListener('DOMContentLoaded',()=>{bind();init()});
})();
