(() => {
'use strict';
const steps=['aguardando','recebido','preparando','saiu para entrega','finalizado'];
const labels={aguardando:'AGUARDANDO',recebido:'RECEBIDO',preparando:'PREPARANDO','saiu para entrega':'SAIU PARA ENTREGA',finalizado:'FINALIZADO'};
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const brl=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let db=null;
function initDb(){try{if(!window.firebase||!window.AKATSUKY_FIREBASE_CONFIG)return false;if(!firebase.apps.length)firebase.initializeApp(window.AKATSUKY_FIREBASE_CONFIG);db=firebase.database();return true}catch(e){console.error('pedido-status',e);return false}}
function normalize(o){if(o?.customerStatus&&steps.includes(o.customerStatus))return o.customerStatus;if(o?.status==='entregue')return 'finalizado';if(o?.status&&steps.includes(o.status))return o.status;return 'aguardando'}
function timeline(status){const idx=Math.max(0,steps.indexOf(status));return `<div class="psTimeline">${steps.map((s,i)=>`<div class="psStep ${i<=idx?'active':''} ${s===status?'current':''}"><span>${i<idx?'✓':i===idx?'●':'○'}</span><b>${labels[s]}</b></div>`).join('')}</div>`}
function renderClient(id,o){const box=document.getElementById('trackingBox');if(!box||!o)return;const st=normalize(o);box.innerHTML=`<div class="psHead"><b>Pedido #${esc(String(id).slice(-6))}</b><span class="psBadge ps-${st.replace(/\s+/g,'-')}">${labels[st]}</span></div><p>Subtotal: <b>${brl(o.subtotal??(Number(o.total||0)-Number(o.deliveryFee||0)))}</b> • Taxa: <b>${brl(o.deliveryFee||0)}</b> • Total: <b>${brl(o.total)}</b></p>${timeline(st)}`;document.getElementById('tracking')?.classList.remove('hidden')}
function startClient(){if(!initDb())return;const id=localStorage.getItem('lastOrder');if(!id)return;const ref=db.ref('orders/'+id);ref.on('value',s=>{const o=s.val();if(!o)return;if(!o.customerStatus&&o.status==='recebido'&&Number(o.createdAt||0)>Date.now()-120000){ref.update({customerStatus:'aguardando'}).catch(()=>{})}renderClient(id,o)})}
function css(){if(document.getElementById('pedidoStatusCss'))return;const s=document.createElement('style');s.id='pedidoStatusCss';s.textContent='.psHead{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-bottom:12px}.psBadge{display:inline-block;padding:7px 11px;border-radius:999px;font-size:11px;font-weight:900}.ps-aguardando{background:#3a0d14;color:#ff6374;border:1px solid #a51d32}.ps-recebido{background:#0d1b15;color:#63e9ac;border:1px solid #246f4d}.ps-preparando{background:#211a0c;color:#ffc14d;border:1px solid #765515}.ps-saiu-para-entrega{background:#171026;color:#c09aff;border:1px solid #543d82}.ps-finalizado{background:#101b24;color:#79c8ff;border:1px solid #2d6d96}.psTimeline{display:grid;grid-template-columns:repeat(5,1fr);gap:5px;margin-top:18px}.psStep{text-align:center;color:#777e8a;font-size:10px}.psStep span{display:block;font-size:18px;margin-bottom:4px}.psStep.active{color:#fff}.psStep.current{font-weight:900}.psAdminBar{display:flex;flex-wrap:wrap;gap:6px;margin-top:12px;padding-top:10px;border-top:1px solid #292d36}.psAdminBar button{padding:8px 10px;border-radius:8px;background:#191c24;color:#fff;border:1px solid #343844;font-size:10px;font-weight:900;cursor:pointer}.psAdminBar button:hover{border-color:#ef1731}.psAdminBar .psAccept{background:#0d1b15;border-color:#246f4d;color:#63e9ac}.psAdminBar .psFinish{background:#17202a;border-color:#2d6d96;color:#79c8ff}@media(max-width:600px){.psTimeline{grid-template-columns:1fr}.psStep{text-align:left}}';document.head.appendChild(s)}
function setStatus(id,status){if(!db)return;const data={customerStatus:status};if(status==='finalizado'){data.status='entregue';data.deliveredAt=firebase.database.ServerValue.TIMESTAMP;data.statusTimes={entregue:firebase.database.ServerValue.TIMESTAMP}}else{data.status=status};db.ref('orders/'+id).update(data).catch(e=>console.error('status',e))}
function paintAdminStatus(el,st){if(!el)return;el.textContent=labels[st]||String(st||'').toUpperCase();el.style.color=st==='aguardando'?'#ff6374':st==='recebido'?'#63e9ac':st==='finalizado'?'#79c8ff':'';el.style.borderColor=st==='aguardando'?'#a51d32':st==='recebido'?'#246f4d':st==='finalizado'?'#2d6d96':'';el.style.background=st==='aguardando'?'#3a0d14':st==='recebido'?'#0d1b15':st==='finalizado'?'#101b24':''}
function paintAllAdminStatuses(snapshot){const data=snapshot.val()||{};const orders=document.getElementById('orders');if(!orders)return;orders.querySelectorAll('.order').forEach(card=>{const timer=card.querySelector('[data-timer]');if(!timer)return;const id=timer.dataset.timer;const o=data[id];if(!o)return;paintAdminStatus(card.querySelector('.status'),normalize(o))})}
function addAdminControls(){const orders=document.getElementById('orders');if(!orders)return;orders.querySelectorAll('.order').forEach(card=>{const timer=card.querySelector('[data-timer]');if(!timer)return;const id=timer.dataset.timer;if(card.querySelector('.psAdminBar'))return;const bar=document.createElement('div');bar.className='psAdminBar';bar.innerHTML='<button class="psAccept" data-ps="recebido">✓ ACEITAR / RECEBIDO</button><button data-ps="preparando">🍣 PREPARANDO</button><button data-ps="saiu para entrega">🛵 SAIU PARA ENTREGA</button><button class="psFinish" data-ps="finalizado">✓ ENTREGUE / FINALIZAR</button>';bar.addEventListener('click',e=>{const b=e.target.closest('[data-ps]');if(b){setStatus(id,b.dataset.ps);b.disabled=true;setTimeout(()=>b.disabled=false,500)}});card.appendChild(bar)})}
function startAdmin(){if(!initDb())return;css();const orders=document.getElementById('orders');if(!orders)return;const obs=new MutationObserver(()=>addAdminControls());obs.observe(orders,{childList:true,subtree:true});db.ref('orders').on('value',snap=>{paintAllAdminStatuses(snap);addAdminControls()});setTimeout(addAdminControls,300)}
function boot(){css();const isAdmin=!!document.getElementById('orders');const isClient=!!document.getElementById('trackingBox');if(isClient)startClient();if(isAdmin)startAdmin()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();